package com.minseo41.subfeed.data.nas

import android.util.Log
import com.minseo41.subfeed.data.CaptionTrack
import com.minseo41.subfeed.data.Chapter
import com.minseo41.subfeed.data.StreamInfo
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONObject
import java.io.IOException
import java.util.concurrent.TimeUnit
import javax.inject.Inject
import javax.inject.Singleton

// NAS 의 yt-dlp 추출 프록시(server/ 의 FastAPI)를 호출하는 클라이언트.
// GET {base}/extract?v={videoId} (X-SubFeed-Secret 헤더) → JSON → StreamInfo.
// 반환되는 streamUrl 은 NAS 가 바이트를 range-proxy 하는 미디어 URL 이라, 앱 입장에선
// 그냥 direct muxed URL 로 취급되어 기존 ExoPlayer 경로를 그대로 탄다.
@Singleton
class NasStreamFetcher @Inject constructor() {

    // 추출은 서버에서 yt-dlp 가 도므로 read 가 길 수 있다. connect 는 짧게, 전체는 callTimeout 으로 bound.
    private val client = OkHttpClient.Builder()
        .connectTimeout(3, TimeUnit.SECONDS)
        .callTimeout(20, TimeUnit.SECONDS)
        .build()

    suspend fun fetch(baseUrl: String, secret: String, videoId: String): StreamInfo =
        withContext(Dispatchers.IO) {
            val url = "${baseUrl.trimEnd('/')}/extract".toHttpUrl().newBuilder()
                .addQueryParameter("v", videoId)
                .build()
            val request = Request.Builder()
                .url(url)
                .apply { if (secret.isNotEmpty()) addHeader("X-SubFeed-Secret", secret) }
                .build()
            val raw = client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    throw IOException("NAS extract HTTP ${response.code}")
                }
                response.body?.string() ?: throw IOException("NAS extract empty body")
            }
            parse(raw).also {
                Log.d(TAG, "fetch OK videoId=$videoId urlHead=${it.streamUrl.take(60)}")
            }
        }

    suspend fun testConnection(baseUrl: String, secret: String): Boolean =
        withContext(Dispatchers.IO) {
            val url = "${baseUrl.trimEnd('/')}/health"
            val request = Request.Builder()
                .url(url)
                .apply { if (secret.isNotEmpty()) addHeader("X-SubFeed-Secret", secret) }
                .build()
            runCatching {
                client.newCall(request).execute().use { it.isSuccessful }
            }.getOrDefault(false)
        }

    private fun parse(raw: String): StreamInfo {
        val json = JSONObject(raw)
        val streamUrl = json.optString("streamUrl")
        if (streamUrl.isEmpty()) throw IOException("NAS extract: streamUrl 없음 — ${raw.take(200)}")

        val captionsJson = json.optJSONArray("captionTracks")
        val captions = buildList {
            if (captionsJson != null) {
                for (i in 0 until captionsJson.length()) {
                    val c = captionsJson.getJSONObject(i)
                    val lang = c.optString("languageCode")
                    add(
                        CaptionTrack(
                            languageCode = lang,
                            displayName = c.optString("displayName", lang),
                            baseUrl = c.optString("baseUrl"),
                            isAutoGenerated = c.optBoolean("isAutoGenerated", false),
                        ),
                    )
                }
            }
        }

        val chaptersJson = json.optJSONArray("chapters")
        val chapters = buildList {
            if (chaptersJson != null) {
                for (i in 0 until chaptersJson.length()) {
                    val ch = chaptersJson.getJSONObject(i)
                    add(Chapter(timeMs = ch.optLong("timeMs"), title = ch.optString("title")))
                }
            }
        }

        return StreamInfo(
            streamUrl = streamUrl,
            captionTracks = captions,
            durationSeconds = json.optLong("durationSeconds"),
            chapters = chapters,
        )
    }

    companion object {
        private const val TAG = "SubFeedNasStream"
    }
}
