package com.minseo41.subfeed.data

data class CaptionTrack(
    val languageCode: String,
    val displayName: String,
    val baseUrl: String,
    val isAutoGenerated: Boolean,
)

data class Chapter(
    val timeMs: Long,
    val title: String,
)

data class StreamInfo(
    val streamUrl: String,
    val captionTracks: List<CaptionTrack>,
    val durationSeconds: Long = 0L,
    val chapters: List<Chapter> = emptyList(),
)
