package com.minseo41.subfeed.data

data class CaptionTrack(
    val languageCode: String,
    val displayName: String,
    val baseUrl: String,
    val isAutoGenerated: Boolean,
)

data class StreamInfo(
    val streamUrl: String,
    val captionTracks: List<CaptionTrack>,
)
